services:
  backend:
    container_name: todo
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=super_user
      - POSTGRES_PASSWORD=super_password
      - POSTGRES_DB=todo
    restart: always
volumes:
  pgdata:
